#!/bin/sh

ADDON_NAME=hvl
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/etc/config/addons/www/${ADDON_NAME}
case "$1" in

  
  init)
  #make it only when user configurated the ip
  if [ -f ${ADDON_DIR}/ip ] 
  then 
	  if [ $(cat /usr/local/etc/config/InterfacesList.xml | grep '<name>HVL</name>' | wc -l ) -eq 0 ]
        then
		echo "Updating InterfaceList.xml"
		my_url=$(cat ${ADDON_DIR}/ip)
		sed -i /usr/local/etc/config/InterfacesList.xml -e "s/<\/interfaces>/\t<ipc>\n\t\t<name>HVL<\/name>\n\t\t<url>xmlrpc:\/\/${my_url}<\/url>\n\t\t<info>HVL<\/info>\n\t<\/ipc>\n<\/interfaces>/"
	  fi
   fi
   ;;
 
   start)
   ;;

   stop)
   ;;
   
   
   restart)
   ;;
   
   info)
	    version=$(cat ${ADDON_DIR}/VERSION)
        echo "Info: <center><b>Homematic Virtual Layer</b></center>"
        echo "Info: <center><br>Aufruf:<br><a href="/addons/hvl" target="_blank">http://IPAdressederCCU/addons/hvl</a></center>"
        echo "Name: Homematic Virtual Layer"
        echo "Version: ${version}"
        echo "Operations: uninstall"
        echo "Config-Url: /addons/${ADDON_NAME}"
        echo "Update: /addons/${ADDON_NAME}/update-check.cgi"
    ;;
   
   
   uninstall)
  	logger -t homematic -p user.info "removing homematic virtual layer"
	  my_url=$(cat ${ADDON_DIR}/ip)
	  sed -i /usr/local/etc/config/InterfacesList.xml -e "s/\t<ipc>\n\t\t<name>HVL<\/name>\n\t\t<url>xmlrpc:\/\/${my_url}<\/url>\n\t\t<info>HVL<\/info>\n\t<\/ipc>\n//"
	  rm -r ${ADDON_DIR}
	  rm -r /usr/local/etc/config/rc.d/ccu_hvl
	 ;;

  *)
	echo "Usage: $0 {init|start|stop|restart|info|uninstall}" >&2
	exit 1
	;;
esac

exit 0