#!/bin/sh
HVLDIR=/usr/local/addons/hvl
CONFIG_URL=/addons/hvl/index.html
CONFIG_DIR=/usr/local/etc/config
PIDFILE=/var/run/hvl.pid
VER=0.0.11
EXEC=sh
EXECARGS=/usr/local/addons/hvl/etc/hvlrun

VER=0.0.11
PSPID=`ps -o pid,comm,args | awk '{if ($2=="node" && $4 ~ /hvl/){print $1}}'`

case "$1" in
  
  init)
	#run postinstall if necessary
	$HVLDIR/etc/postinstall.sh

  	  if [ $(cat /usr/local/etc/config/InterfacesList.xml | grep '<name>HVL</name>' | wc -l ) -eq 0 ]
        then
		sed -i /usr/local/etc/config/InterfacesList.xml -e "s/<\/interfaces>/\t<ipc>\n\t\t<name>HVL<\/name>\n\t\t<url>xmlrpc:xmlrpc:\/\/127.0.0.1:8301<\/url>\n\t\t<info>HVL<\/info>\n\t<\/ipc>\n<\/interfaces>/"
	  fi
	  start-stop-daemon --start --quiet --oknodo --make-pidfile --background  --pidfile $PIDFILE --exec $EXEC $EXECARGS
	  logger -t homematic -p user.info "started homematic virtual layer"

  ;;

  
  ""|start)


  ;;

  stop)
	start-stop-daemon --stop --quiet  --oknodo  --retry 5  --pidfile $PIDFILE

	if [ -e $PIDFILE ];then
      rm -f $PIDFILE
    fi

	logger -t homematic -p user.info "stopped homematic virtual layer"
	;;

  restart)
  	start-stop-daemon --stop --quiet  --oknodo  --retry 5  --pidfile $PIDFILE

    if [ -e $PIDFILE ];then
      rm -f $PIDFILE
    fi
  	
	sleep 2
	start-stop-daemon --start --quiet --oknodo --make-pidfile --background  --pidfile $PIDFILE --exec $EXEC $EXECARGS

	logger -t homematic -p user.info "started (restart) homematic virtual layer"
	;;

  info)
	echo "Info: <center><b>Homematic Virtual Layer</b></center>"
	echo "Name: HVL"
	echo "Version: $VER"
	echo "Operations: uninstall"
	echo "Config-Url: $CONFIG_URL"
	;;

  uninstall)
	logger -t homematic -p user.info "removing homematic virtual layer"
	kill -KILL $PSPID 2>/dev/null
	node /usr/local/addons/hvl/etc/hm_addon.js hvl
	rm -R /usr/local/addons/hvl
    rm /usr/local/etc/config/rc.d/hvl 
    rm /etc/logrotate.d/hvl.conf
	sed -i /usr/local/etc/config/InterfacesList.xml -e "s/\t<ipc>\n\t\t<name>HVL<\/name>\n\t\t<url>xmlrpc:xmlrpc:\/\/127.0.0.1:8301<\/url>\n\t\t<info>HVL<\/info>\n\t<\/ipc>\n//"
	/usr/local/addons/hvl/etc/remove_hvl_object
	;;

  *)
	echo "Usage: $0 {init|start|stop|restart|uninstall}" >&2
	exit 1
	;;
esac

exit 0