#!/bin/sh
HVLDIR=/usr/local/addons/hvl
CONFIG_URL=/addons/hvl/index.html
CONFIG_DIR=/usr/local/etc/config
PIDFILE=/var/run/hvl.pid
STARTRC=/etc/init.d/S51hvl
VER=0.0.5
PSPID=`ps -o pid,comm,args | awk '{if ($2=="node" && $3 ~ /hvl/){print $1}}'`

case "$1" in
  ""|start)
	if [ ! -h $STARTRC ]
	then
	  mount -o remount,rw /
	  ln -sf $CONFIG_DIR/rc.d/hvl $STARTRC
	  mount -o remount,ro /
	fi

	#run postinstall if necessary
	$HVLDIR/etc/postinstall.sh

	if [ "$PSPID" = "" ]
	then
	  $HVLDIR/node/bin/node $HVLDIR/node_modules/homematic-virtual-interface/lib/index.js -C $CONFIG_DIR/hvl/ >>/var/log/hvl.log &
	  logger -t homematic -p user.info "started homematic virtual layer"
	fi
	;;

  stop)
  	if [ "$PSPID" != "" ]
  	then
	  kill -TERM $PSPID 2>/dev/null
	  sleep 1
	  kill -0 $PSPID 2>/dev/null
	  if [ $? -eq 0 ]
	  then
	    sleep 10
	    kill -KILL $PSPID 2>/dev/null
	  fi
	  logger -t homematic -p user.info "stopped homematic virtual layer"
	fi
	;;

  restart)
  	if [ "$PSPID" != "" ]
  	then
	  kill -TERM $PSPID 2>/dev/null
	  sleep 1
	  kill -0 $PSPID 2>/dev/null
	  if [ $? -eq 0 ]
	  then
	    sleep 10
	    kill -KILL $PSPID 2>/dev/null
	  fi
	  logger -t homematic -p user.info "stopped homematic virtual layer for restart"
	fi
	$HVLDIR/node/bin/node $HVLDIR/node_modules/homematic-virtual-interface/lib/index.js -C $CONFIG_DIR/hvl/ >>/dev/null &
	logger -t homematic -p user.info "started (restart) homematic virtual layer"
	;;

  info)
	echo "Info: <center><b>Homematic Virtual Layer</b></center>"
	echo "Name: HVL"
	echo "Version: $VER"
	echo "Operations: uninstall"
	echo "Config-Url: $CONFIG_URL"
	;;

  uninstall)
	logger -t homematic -p user.info "removing homematic virtual layer"
	kill -KILL $PSPID 2>/dev/null
	/usr/local/addons/hvl/etc/update_addon hvl
	rm -R /usr/local/addons/hvl
    rm /usr/local/etc/config/rc.d/hvl 
	mount -o remount,rw /
    rm /etc/init.d/S51hvl
    rm /etc/logrotate.d/hvl.conf
	sed -i /etc/config_templates/InterfacesList.xml -e "s/<ipc><name>HVL<\/name><url>xmlrpc:\/\/127.0.0.1:8301<\/url><info>HVL<\/info><\/ipc>//"
	sed -i /usr/local/etc/config/InterfacesList.xml -e "s/<ipc><name>HVL<\/name><url>xmlrpc:\/\/127.0.0.1:8301<\/url><info>HVL<\/info><\/ipc>//"
	mount -o remount,ro /
	/usr/local/addons/hvl/etc/remove_hvl_object
	;;

  *)
	echo "Usage: $0 {start|stop|restart|uninstall}" >&2
	exit 1
	;;
esac

exit 0