#!/bin/sh
### BEGIN INIT INFO
# Provides:	Homematic Virtual Interface
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


dir="/home/hmvi/node_modules/homematic-virtual-interface"
cmd="bin/hmviservice"
user="hmvi"

sudo -u "$user" $dir/$cmd $1
exit 0

