#!/bin/sh
ADDONENAME=hvl
ADDONDIR=/usr/local/etc/config/addons/$ADDONENAME
WWWDIR=/usr/local/etc/config/addons/www/$ADDONENAME
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config

mkdir -p /mnt

if [ "$1" = "" ]
then
	exit 1
fi

	mount -t ubifs ubi0:root /mnt
	mount -t ubifs ubi1:user /usr/local
	
	#www
	mkdir -p $WWWDIR
	# copy addon
	cp -R hvl/* $WWWDIR
	chmod 775 $WWWDIR

	# copy startup script
	cp -R rc.d/* $RCD_DIR

	# make it run
	chmod +x $RCD_DIR/ccu_hvl
	
	# make it run early
	
	ln -s $RCD_DIR/ccu_hvl /etc/init.d/S59hvl


	umount /usr/local
	umount /mnt