#!/bin/sh
ADDONENAME=hvl
ADDONDIR=/usr/local/etc/config/addons/$ADDONENAME
WWWDIR=/usr/local/etc/config/addons/www/$ADDONENAME
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config

mkdir -p /mnt

if [ "$1" = "" ]
then
	exit 1
fi

	#www
	mkdir -p $WWWDIR
	# copy addon
	cp -R hvl/* $WWWDIR
	cp VERSION $WWWDIR
	chmod 775 $WWWDIR

	# copy startup script
	cp -R rc.d/* $RCD_DIR
	# make it run
	chmod +x $RCD_DIR/ccu_hvl
	
	/usr/local/etc/config/addons/www/hvl/update_addon hvl /usr/local/etc/config/addons/www/hvl/hvl_addon.cfg
	
	sync
